/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "outline-variant": "#adb3b4",
        "on-error-container": "#782232",
        "on-error": "#fff7f7",
        "surface-container": "#ebeeef",
        "error-dim": "#4f0116",
        "surface-variant": "#dde4e5",
        "on-primary-fixed": "#3f3f42",
        "on-secondary-fixed": "#004a1c",
        "on-surface-variant": "#5a6061",
        "secondary-fixed-dim": "#70ed8a",
        "tertiary-fixed-dim": "#e0dee9",
        "error-container": "#ff8b9a",
        "on-secondary-container": "#005f27",
        "inverse-on-surface": "#9c9d9d",
        "on-surface": "#2d3435",
        "on-tertiary-fixed-variant": "#62626b",
        "primary": "#5f5e61",
        "surface-dim": "#d4dbdd",
        "tertiary-dim": "#52525b",
        "on-background": "#2d3435",
        "primary-fixed": "#e4e1e6",
        "secondary-container": "#7ffc97",
        "on-secondary-fixed-variant": "#006a2c",
        "surface-container-low": "#f2f4f4",
        "on-primary": "#faf7fb",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#7ffc97",
        "on-tertiary": "#faf8ff",
        "on-secondary": "#e9ffe6",
        "tertiary-container": "#efecf8",
        "outline": "#757c7d",
        "inverse-surface": "#0c0f0f",
        "primary-container": "#e4e1e6",
        "primary-dim": "#535255",
        "surface-tint": "#5f5e61",
        "on-primary-fixed-variant": "#5c5b5e",
        "inverse-primary": "#f9f5fa",
        "error": "#9e3f4e",
        "on-tertiary-fixed": "#45454e",
        "secondary-dim": "#006127",
        "tertiary-fixed": "#efecf8",
        "on-primary-container": "#525155",
        "surface-container-highest": "#dde4e5",
        "surface": "#f9f9f9",
        "surface-bright": "#f9f9f9",
        "secondary": "#006e2e",
        "tertiary": "#5e5e67",
        "on-tertiary-container": "#585861",
        "surface-container-high": "#e4e9ea",
        "primary-fixed-dim": "#d6d3d7",
        "background": "#f9f9f9",
        zinc: {
          950: '#09090b',
        }
      },
      fontFamily: {
        sans: ['Inter', 'Noto Sans', 'sans-serif'],
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        logo: ['Barriecito', 'cursive'],
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
        '2xl': '1rem',
      }
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
}
