"""add_content_to_panel_and_make_datasource_optional

Revision ID: 0db20ec9d3d1
Revises: d1f703bccbde
Create Date: 2026-04-02 16:42:52.312994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0db20ec9d3d1'
down_revision: Union[str, Sequence[str], None] = 'd1f703bccbde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboardpanel', sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('dashboardpanel', 'data_source_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('dashboardpanel', 'natural_language_query',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('dashboardpanel', 'generated_sql',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dashboardpanel', 'generated_sql',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dashboardpanel', 'natural_language_query',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('dashboardpanel', 'data_source_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('dashboardpanel', 'content')
    # ### end Alembic commands ###
