"""initial

Revision ID: 42a4bae012e1
Revises: 
Create Date: 2026-04-01 22:39:43.952414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '42a4bae012e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datasource',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('database', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('encrypted_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasource_name'), 'datasource', ['name'], unique=False)
    op.create_table('dashboardpanel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('natural_language_query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generated_sql', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chart_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('layout', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboard.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['datasource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schemamanifest',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('data_source_id', sa.Uuid(), nullable=False),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=True),
    sa.Column('ai_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['datasource.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queryhistory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('panel_id', sa.Uuid(), nullable=True),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generated_sql', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['dashboardpanel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('queryhistory')
    op.drop_table('schemamanifest')
    op.drop_table('dashboardpanel')
    op.drop_index(op.f('ix_datasource_name'), table_name='datasource')
    op.drop_table('datasource')
    op.drop_table('dashboard')
    # ### end Alembic commands ###
