"""Add sample_rows to SchemaManifest

Revision ID: 46ab38ffec3b
Revises: 249e92d1e24b
Create Date: 2026-04-02 11:21:49.292776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46ab38ffec3b'
down_revision: Union[str, Sequence[str], None] = '249e92d1e24b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schemamanifest', sa.Column('sample_rows', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schemamanifest', 'sample_rows')
    # ### end Alembic commands ###
