"""Add chart_config to DashboardPanel

Revision ID: 8f96b42e1980
Revises: 46ab38ffec3b
Create Date: 2026-04-02 12:50:47.446605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f96b42e1980'
down_revision: Union[str, Sequence[str], None] = '46ab38ffec3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboardpanel', sa.Column('chart_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboardpanel', 'chart_config')
    # ### end Alembic commands ###
