"""add default chart color to dashboard

Revision ID: a9e2ad1f7292
Revises: 0db20ec9d3d1
Create Date: 2026-04-04 19:59:40.399457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'a9e2ad1f7292'
down_revision: Union[str, Sequence[str], None] = '0db20ec9d3d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard', sa.Column('default_chart_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='#6366f1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboard', 'default_chart_color')
    # ### end Alembic commands ###
