"""remove custom_css from dashboard

Revision ID: d1f703bccbde
Revises: 8453fa35653a
Create Date: 2026-04-02 16:28:55.032688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1f703bccbde'
down_revision: Union[str, Sequence[str], None] = '8453fa35653a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboard', 'custom_css')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboard', sa.Column('custom_css', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
