"""Add DashboardSnapshot

Revision ID: da01f14f6b34
Revises: a9e2ad1f7292
Create Date: 2026-04-05 05:55:38.412832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'da01f14f6b34'
down_revision: Union[str, Sequence[str], None] = 'a9e2ad1f7292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcpconnection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('server_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboardsnapshot',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('dashboard_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snapshot_data', sa.JSON(), nullable=True),
    sa.Column('filter_settings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboard.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboardpanel', schema=None) as batch_op:
        batch_op.alter_column('data_source_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)
        batch_op.alter_column('natural_language_query',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('generated_sql',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dashboardpanel', schema=None) as batch_op:
        batch_op.alter_column('generated_sql',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('natural_language_query',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('data_source_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)

    op.drop_table('dashboardsnapshot')
    op.drop_table('mcpconnection')
    # ### end Alembic commands ###
